### ISSUE TITLE
3.3 release

### ISSUE THREAD

**Issue by lazka** [elelay/quodlibet-osx-bundle#10]
I'm going to do a 3.3 release this month. Would be cool if we can announce the osx bundle with it.

Regarding the existing issues: We can just disable mmkeys and tooltips for this first release. IMHO a non feature complete release is better than none at all . Thoughts?

**Comment by elelay** [comment]
[ExFalso 3.3.0_0](/elelay/quodlibet-osx-bundle/releases/download/Quodlibet-3.3.0_0/ExFalso-3.3.0_0.zip) ( [checksum](/elelay/quodlibet-osx-bundle/releases/download/Quodlibet-3.3.0_0/ExFalso-3.3.0_0.zip.sha256) )

[QuodLibet 3.3.0_0](/elelay/quodlibet-osx-bundle/releases/download/Quodlibet-3.3.0_0/QuodLibet-3.3.0_0.zip) ( [checksum](/elelay/quodlibet-osx-bundle/releases/download/Quodlibet-3.3.0_0/Quodlibet-3.3.0_0.zip.sha256) )
