### ISSUE TITLE
Move to the QL repo?

### ISSUE THREAD

**Issue by lazka** [elelay/quodlibet-osx-bundle#13]
Would you be OK if this was moved into the QL mercurial repo? Or do you have any other plans? (I remember some talk about this, but can't find any related emails right now)

**Comment by elelay** [comment]
OK to move (you mean to a subdirectory of quodlibet repo ?)
What about the issue tracker?

**Comment by lazka** [comment]
Yes, something like <repo>/osx_bundle. I can create bugs referencing the issues here and give you access to upload files to bitbucket.

But, I don't mind if things stay as they are now.

**Comment by lazka** [comment]
I've integrated things into the main QL repo now: https://github.com/quodlibet/quodlibet/tree/master/osx_bundle and released a new 3.4.1 bundle

**Comment by elelay** [comment]
I'll test the new 3.4.1 bundle.
From looking at the files, it seems you don't remove pyc and pyo.
Also you don't use the provenance.pl script to provide traceability to the sources.
Is this deliberate or an overlook ?

Cheers,

**Comment by lazka** [comment]
Thanks for having a look.

Having pyc in addition to py gives me a 200ms load speedup on Debian for the quodlibet package alone. pyo could be removed I guess. And actually all py files could be removed as well to save space if we do a ``python -m compileall`` on the bundle; this is what we do on Windows.

I guess the purpose of provenance.pl is to help debugging what goes into the bundle based on the bundler config? I didn't need it as you did all that work already :) Or is there another usecase? I'll look into integrating it again.

**Comment by lazka** [comment]
btw. I've bumped the min version to 10.7 as 10.6+7 don't seem to be getting security updates anymore. If that's a problem I can revert that back.

**Comment by elelay** [comment]
Finally got around to test it and it works fine!

.pyc and .po: I thought there were absolute paths in them so had to be recompiled on first run anyway.

provenance.pl: that's intended as traceability to the source packages. I didn't provide a mean to download them directly, because the point was to provide a binary download, so it was a step in direction of compliance. Also in case a concerned user checks for vulnerability in bundled version of gnutls, for instance...

revbump to 10.7: I'd rather see it reverted. I'm still on 10.6 at home, regardless of lack of security updates. Why force an upgrade on users?

Cheers,

**Comment by lazka** [comment]
> .pyc and .po: I thought there were absolute paths in them so had to be recompiled on first run anyway.

I think those are only used for tracebacks. At least I haven't seen any problems under Windows using pyc only.

> provenance.pl: that's intended as traceability to the source packages. I didn't provide a mean to download them directly, because the point was to provide a binary download, so it was a step in direction of compliance. Also in case a concerned user checks for vulnerability in bundled version of gnutls, for instance...

I've added something similar back now and included the output directly in the bundle under Contents/Resources/content.txt. See here for example: https://bpaste.net/raw/156e3055ea25

> revbump to 10.7: I'd rather see it reverted. I'm still on 10.6 at home, regardless of lack of security updates. Why force an upgrade on users?

The newest one uses 10.6 again. Building should still happen under 10.7+ so the new API usages get compiled in.

**Comment by lazka** [comment]
oops, didn't mean to close

**Comment by elelay** [comment]
Thanks @lazka! You do great work for QuodLibet and I'm really happy to see the osx bundle a full part of the development. I'll push a cleanup commit with links to the main repo.

Cheers,
