### ISSUE TITLE
mmkeys

### ISSUE THREAD

**Issue by lazka** [elelay/quodlibet-osx-bundle#8]
So we have a tracker bug..

I've moved the processing into a thread, see: https://code.google.com/p/quodlibet/source/detail?r=a2ee012ad1afd65b1a8210a96d99e73fcb1ebeec

Maybe that helps. I haven't tested it with media keys because I have none.

**Comment by elelay** [comment]
So the plan is to release a gkt-ised SPMediaKeyTap library.
Not sure when/if I'll tackle it...
Just let me know if you start working on it.
I've nonetheless opened a [pull request](https://github.com/nevyn/SPMediaKeyTap/pull/31) to include quodlibet.
